### Different form of slicing

In [6]:
import numpy as np;
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)
slice2=arr[::2]
print(slice2)
slice3=arr[::-3]
print(slice3)

[3 4 5 6]
[1 3 5 7 9]
[9 6 3]


## Slicing multidimensional array

In [7]:
import numpy as np;
arr=np.array([[2,3,4],[4,4,5]])
string=arr[0:2,:3]
print(string)

[[2 3 4]
 [4 4 5]]


#### Extracting

In [8]:
col1=arr[:,0]
print(col1)
row1=arr[0,:]
print(row1)
col3=arr[0:2:1]
print(col3)

[2 4]
[2 3 4]
[[2 3 4]
 [4 4 5]]


##### Array indexing

In [9]:
import numpy as np;
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0,0])

10


In [10]:
import numpy as np;
arr=np.array([10,20,30,40])   #basic indexing
print(arr[0])

10


In [11]:
import numpy as np;
arr=np.array([10,20,30,40])    #negative inndexing
print(arr[-1])


40


In [12]:
import numpy as np;
s=np.array([[4,5,4],[3,2,1]])   #slicing indexing
print(arr[1:3])

[20 30]


In [13]:
import numpy as np;
a=np.array([10,20,30,40,50])     #boolean indexing
f=a>25
g=a[f]
print(g)

[30 40 50]


##### JOINIING

In [14]:
import numpy as np;
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])   #horizontal joining
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
result=np.vstack((arr1,arr2))  #vertical joining
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
result=np.dstack((arr1,arr2))  #depth joining
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


##### ARRAY SPLITTING

In [17]:
import numpy as np;
arr1=np.array([1,2,3,4,5,5])
result=np.split(arr1,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 5])]
