In [13]:
import numpy as np
b = np.array([[10,20,30],[40,50,60]])
print("two dimensional array:",b)

two dimensional array: [[10 20 30]
 [40 50 60]]


In [17]:
import numpy as np
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("\nthree dimensional array:\n",b)


three dimensional array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [19]:
import numpy as np
b = np.zeros((3,3))
print("\n Array with all zeros:\n",b)


 Array with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
import numpy as np
b = np. random.random((2,2))
print("\n random value:\n",b)


 random value:
 [[0.87188017 0.06843263]
 [0.25405638 0.27863133]]


In [25]:
import numpy as np
b = np.arange(0,20,4)
print("\nsequence array:\n",b)


sequence array:
 [ 0  4  8 12 16]


In [33]:
 import numpy as np
b = np.array([[10,20],[40,50],[70,80]])
newarr=b.reshape(2,3)
print("\nthree dimensional array:\n",b)
print("\n reshaped array[2,3]:\n",newarr)


three dimensional array:
 [[10 20]
 [40 50]
 [70 80]]

 reshaped array[2,3]:
 [[10 20 40]
 [50 70 80]]


In [35]:
import numpy as np
b = np.array([10,20,30])
print("one dimensional array:",b)

one dimensional array: [10 20 30]


In [49]:
import numpy as np
original = np.array([[10,20],[40,50],[70,80]])
flat=original.flatten()
print("\n Original array:\n",b)
print("\n flatten array:\n",flat)


 Original array:
 [[10 20]
 [40 50]
 [70 80]]

 flatten array:
 [10 20 40 50 70 80]


In [53]:
import numpy as np
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("\nnumber of dimensional:\n",b.ndim)


number of dimensional:
 2
