In [1]:
# i) 3x4 array with random values
import numpy as np
a=np.random.random((3,4))
print(a)

[[0.2761182  0.1779579  0.95809579 0.21184023]
 [0.64543414 0.63450512 0.89987053 0.75882962]
 [0.24823507 0.889914   0.37200124 0.67587209]]


In [2]:
import numpy as np
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
import numpy as np
a=np.arange(5,31,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Dimensions:",a.ndim)
print("\nShape:",a.shape)
print("\nDatatype:",a.dtype)

Dimensions: 2

Shape: (2, 3)

Datatype: int64


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.flatten())

[1 2 3 4 5 6 7 8 9]
